(() => {
  const privacy={
    en:{eyebrow:'WEBSITE PRIVACY NOTICE',title:'Privacy, without the fine print theatre.',intro:'This notice explains what the LDU website collects, why it is used and what choices you have. LDU does not sell personal data and does not load optional analytics before consent.',updated:'Last updated · 11 September 2026',referenceTitle:'Regulatory reference',referenceBody:'This website notice is structured around the Saudi Personal Data Protection Law (PDPL) and SDAIA privacy-policy guidance. It is an operational website notice, not legal advice.',back:'Back to project intake ↗',sections:[
      ['Who controls the data','For website inquiries, LDU acts as the party deciding why and how the submitted information is used. LDU is based in Riyadh, Saudi Arabia.'],
      ['What we collect','The project-intake form may collect your name, organisation, role, work email, market, project type, indicative budget, timeline and the project information you choose to provide. Do not submit sensitive personal data, confidential contracts or financial-account information through the public form.'],
      ['Why we collect it','We use inquiry data to assess project fit, respond to you, plan a possible commercial conversation, protect the integrity of the website and maintain an appropriate record of the inquiry. Optional analytics are used only after your consent.'],
      ['Analytics and cookies','Necessary site functions do not require marketing cookies. If analytics identifiers are configured, Google Analytics and/or Meta Pixel load only after you choose “Allow analytics”. You can decline and continue using the site.'],
      ['How data is shared','LDU does not sell your personal data. Data may be handled by service providers used to host the site, process the secure intake or provide analytics, but only for the relevant service and subject to applicable safeguards.'],
      ['International processing','Some technical providers may process data outside Saudi Arabia. Where this occurs, LDU should use providers and transfer mechanisms consistent with applicable Saudi data-transfer requirements.'],
      ['Retention and deletion','Inquiry data is kept only for as long as reasonably necessary to evaluate and respond to the inquiry, maintain business records where needed, or meet legal obligations. Data should be deleted or anonymised when it is no longer required for those purposes.'],
      ['Your rights','Subject to the PDPL and its implementing regulations, you may have rights to be informed, access your personal data, request correction, request destruction where applicable, and withdraw consent where processing depends on consent.'],
      ['Security','The public website does not expose source archives or a visible contact email. The production intake endpoint should validate input, restrict allowed origins, apply anti-bot controls and keep secrets server-side. No internet service can be guaranteed absolutely secure.'],
      ['How to contact us','Use the project-intake page and select the appropriate request context, or use the direct phone line published on the site. Privacy requests should be verified before personal data is disclosed, corrected or deleted.']
    ]},
    ar:{eyebrow:'إشعار خصوصية الموقع',title:'خصوصية بلا مسرحية الحروف الصغيرة.',intro:'يوضح هذا الإشعار ما الذي يجمعه موقع LDU، ولماذا تتم معالجته، وما الخيارات المتاحة لك. لا تبيع LDU البيانات الشخصية، ولا تُحمّل أدوات التحليل الاختيارية قبل الموافقة.',updated:'آخر تحديث · 11 سبتمبر 2026',referenceTitle:'المرجع التنظيمي',referenceBody:'تمت هيكلة هذا الإشعار بما يتوافق مع مبادئ نظام حماية البيانات الشخصية السعودي وإرشادات سدايا الخاصة بسياسات الخصوصية. وهو إشعار تشغيلي للموقع وليس استشارة قانونية.',back:'العودة إلى استقبال المشاريع ↗',sections:[
      ['من يتحكم في البيانات','بالنسبة لطلبات الموقع، تحدد LDU غرض استخدام المعلومات المرسلة وكيفية معالجتها. مقر LDU في الرياض، المملكة العربية السعودية.'],
      ['ما الذي نجمعه','قد يجمع نموذج استقبال المشاريع الاسم والجهة والمسمى الوظيفي وبريد العمل والسوق ونوع المشروع والميزانية التقديرية والجدول الزمني والمعلومات التي تختار تقديمها عن المشروع. لا ترسل بيانات حساسة أو عقوداً سرية أو معلومات حسابات مالية عبر النموذج العام.'],
      ['لماذا نجمعه','نستخدم بيانات الطلب لتقييم ملاءمة المشروع والرد عليك والتحضير لمحادثة تجارية محتملة وحماية سلامة الموقع والاحتفاظ بسجل مناسب للطلب. لا تُستخدم التحليلات الاختيارية إلا بعد موافقتك.'],
      ['التحليلات وملفات الارتباط','وظائف الموقع الأساسية لا تحتاج ملفات تعريف ارتباط تسويقية. إذا تم تفعيل معرفات التحليل، فلن يتم تحميل Google Analytics أو Meta Pixel إلا بعد اختيارك السماح بالتحليلات. يمكنك الرفض والاستمرار في استخدام الموقع.'],
      ['مشاركة البيانات','لا تبيع LDU بياناتك الشخصية. قد تعالج البيانات جهات تقدم الاستضافة أو استقبال الطلبات الآمن أو خدمات التحليل، وذلك فقط في حدود الخدمة ذات الصلة ومع الضمانات النظامية المناسبة.'],
      ['المعالجة خارج المملكة','قد يعالج بعض مزودي الخدمات التقنية البيانات خارج السعودية. وعند حدوث ذلك، ينبغي استخدام مزودين وآليات نقل متوافقة مع المتطلبات السعودية السارية لنقل البيانات.'],
      ['الاحتفاظ والإتلاف','يتم الاحتفاظ ببيانات الطلب فقط للمدة اللازمة بشكل معقول لتقييم الطلب والرد عليه أو للاحتفاظ بسجلات عمل عند الحاجة أو للوفاء بالالتزامات النظامية، ثم تُحذف أو تُجعل مجهولة الهوية عند انتفاء الحاجة.'],
      ['حقوقك','وفقاً لنظام حماية البيانات الشخصية ولوائحه التنفيذية، قد تشمل حقوقك العلم بالمعالجة والوصول إلى بياناتك وطلب التصحيح وطلب الإتلاف عند انطباقه وسحب الموافقة عندما تعتمد المعالجة عليها.'],
      ['الأمن','لا يكشف الموقع العام أرشيفات المصدر أو عنوان بريد ظاهر. وينبغي لنقطة استقبال الطلبات الإنتاجية التحقق من المدخلات وتقييد المصادر المسموحة وتطبيق مكافحة الروبوتات وحفظ الأسرار على الخادم. لا توجد خدمة إنترنت يمكن ضمان أمنها بشكل مطلق.'],
      ['التواصل','استخدم صفحة استقبال المشاريع وحدد سياق الطلب المناسب، أو استخدم رقم الهاتف المباشر المنشور في الموقع. يجب التحقق من هوية صاحب الطلب قبل الإفصاح عن بيانات شخصية أو تصحيحها أو حذفها.']
    ]},
    fr:{eyebrow:'AVIS DE CONFIDENTIALITÉ DU SITE',title:'La confidentialité, sans théâtre des petits caractères.',intro:'Cet avis explique ce que le site LDU collecte, pourquoi ces données sont utilisées et quels choix vous avez. LDU ne vend pas de données personnelles et ne charge pas d’analytics optionnels avant consentement.',updated:'Dernière mise à jour · 11 septembre 2026',referenceTitle:'Référence réglementaire',referenceBody:'Cet avis suit la structure du Saudi Personal Data Protection Law (PDPL) et des recommandations SDAIA relatives aux politiques de confidentialité. Il s’agit d’un avis opérationnel du site, pas d’un conseil juridique.',back:'Retour au brief projet ↗',sections:[
      ['Responsable des données','Pour les demandes via le site, LDU détermine pourquoi et comment les informations soumises sont utilisées. LDU est basée à Riyad, Arabie saoudite.'],['Données collectées','Le formulaire peut collecter nom, organisation, fonction, e-mail professionnel, marché, type de projet, budget indicatif, calendrier et informations de projet que vous choisissez de fournir. N’envoyez pas de données sensibles, contrats confidentiels ou informations bancaires via le formulaire public.'],['Finalités','Les données servent à évaluer le projet, répondre, préparer une éventuelle conversation commerciale, protéger l’intégrité du site et conserver un historique approprié. Les analytics optionnels ne sont utilisés qu’après consentement.'],['Analytics et cookies','Les fonctions nécessaires du site n’exigent pas de cookies marketing. Si des identifiants analytics sont configurés, Google Analytics et/ou Meta Pixel ne se chargent qu’après votre accord.'],['Partage','LDU ne vend pas vos données. Des prestataires peuvent les traiter pour l’hébergement, l’intake sécurisé ou les analytics, uniquement pour le service concerné et avec les garanties applicables.'],['Traitement international','Certains prestataires techniques peuvent traiter des données hors d’Arabie saoudite. Les mécanismes de transfert doivent respecter les exigences saoudiennes applicables.'],['Conservation','Les données de demande sont conservées uniquement aussi longtemps que nécessaire pour évaluer et traiter la demande, tenir des dossiers légitimes ou respecter les obligations légales, puis supprimées ou anonymisées.'],['Vos droits','Sous réserve du PDPL et de ses règlements, vous pouvez notamment être informé, accéder à vos données, demander leur correction ou destruction lorsque cela s’applique et retirer un consentement.'],['Sécurité','Le site public n’expose ni archives sources ni adresse e-mail visible. L’endpoint de production doit valider les entrées, restreindre les origines, utiliser des contrôles anti-bot et garder les secrets côté serveur.'],['Contact','Utilisez le formulaire de prise de brief ou la ligne directe du site. Une vérification d’identité peut être nécessaire avant divulgation, correction ou suppression de données.']
    ]},
    es:{eyebrow:'AVISO DE PRIVACIDAD DEL SITIO',title:'Privacidad, sin teatro de letra pequeña.',intro:'Este aviso explica qué recopila el sitio de LDU, por qué se utiliza y qué opciones tienes. LDU no vende datos personales y no carga analytics opcionales antes del consentimiento.',updated:'Última actualización · 11 de septiembre de 2026',referenceTitle:'Referencia regulatoria',referenceBody:'Este aviso sigue la estructura de la Saudi Personal Data Protection Law (PDPL) y la guía de SDAIA sobre políticas de privacidad. Es un aviso operativo del sitio, no asesoramiento legal.',back:'Volver al briefing del proyecto ↗',sections:[
      ['Responsable de los datos','Para las consultas del sitio, LDU decide por qué y cómo se utilizan los datos enviados. LDU tiene su sede en Riad, Arabia Saudí.'],['Datos que recopilamos','El formulario puede recopilar nombre, organización, cargo, correo de trabajo, mercado, tipo de proyecto, presupuesto indicativo, calendario e información del proyecto que decidas aportar. No envíes datos sensibles, contratos confidenciales o información bancaria por el formulario público.'],['Finalidades','Usamos los datos para evaluar el encaje del proyecto, responder, preparar una posible conversación comercial, proteger la integridad del sitio y mantener un registro adecuado. Los analytics opcionales solo se usan tras tu consentimiento.'],['Analytics y cookies','Las funciones necesarias no requieren cookies de marketing. Si se configuran identificadores, Google Analytics y/o Meta Pixel solo se cargan después de tu aprobación.'],['Compartición','LDU no vende tus datos. Proveedores de hosting, intake seguro o analytics pueden procesarlos solo para el servicio correspondiente y con las salvaguardas aplicables.'],['Procesamiento internacional','Algunos proveedores técnicos pueden procesar datos fuera de Arabia Saudí. Los mecanismos de transferencia deben ajustarse a los requisitos saudíes aplicables.'],['Retención','Los datos de consulta se conservan solo el tiempo razonablemente necesario para evaluarla y responder, mantener registros legítimos o cumplir obligaciones legales; después se eliminan o anonimizan.'],['Tus derechos','Sujeto al PDPL y sus reglamentos, puedes tener derechos de información, acceso, corrección, destrucción cuando corresponda y retirada del consentimiento cuando el tratamiento dependa de él.'],['Seguridad','El sitio público no expone archivos fuente ni un correo visible. El endpoint de producción debe validar entradas, restringir orígenes, aplicar controles anti-bot y mantener secretos en el servidor.'],['Contacto','Usa el formulario de briefing o la línea directa publicada. Puede ser necesaria una verificación de identidad antes de divulgar, corregir o eliminar datos personales.']
    ]}
  };
  const terms={
    en:{eyebrow:'WEBSITE TERMS OF USE',title:'Use the site. Keep the attribution clean.',intro:'These terms govern use of the public LDU website. They do not replace a proposal, statement of work, contract or rights agreement.',updated:'Last updated · 11 September 2026',back:'Back to project intake ↗',sections:[
      ['Purpose of the site','The site presents LDU’s positioning, method, capabilities and selected credentials. Information is provided for general business and informational purposes.'],['Founder-led work','Where work was delivered by a founder at a previous company, the site labels it as founder-led work. Those credentials are not represented as direct LDU client engagements.'],['Intellectual property','Unless otherwise stated, the LDU wordmark, ibex, visual system, original copy, layouts and site code are protected materials. No licence is granted except the limited right to view the site.'],['Media and third-party marks','Brand names and third-party marks are used only to identify documented credentials. Rights in those marks remain with their respective owners. Event footage or photography should not be published unless LDU has the required rights or permission.'],['No offer or guarantee','Nothing on the site is a binding offer, promise of availability, performance guarantee or commitment to a particular commercial result. Scope, fees, rights and responsibilities are agreed separately in writing.'],['Acceptable use','Do not interfere with the site, attempt unauthorised access, automate abusive requests, misrepresent the content, or remove attribution. Defensive security testing requires prior written authorisation.'],['External services','The site may link to third-party services such as Instagram or analytics providers. Their terms and privacy practices apply independently.'],['Governing context','These terms are intended for a Saudi-based business website and should be interpreted in the context of applicable laws of the Kingdom of Saudi Arabia, subject to any binding agreement between the parties.'],['Changes','LDU may update the site and these terms. The date above identifies the version currently published.'],['Contact','For commercial enquiries or questions about these terms, use the project-intake page or the direct line published on the site.']
    ]},
    ar:{eyebrow:'شروط استخدام الموقع',title:'استخدم الموقع. وحافظ على النسبة نظيفة.',intro:'تنظم هذه الشروط استخدام موقع LDU العام، ولا تستبدل العرض أو نطاق العمل أو العقد أو اتفاقيات الحقوق.',updated:'آخر تحديث · 11 سبتمبر 2026',back:'العودة إلى استقبال المشاريع ↗',sections:[
      ['غرض الموقع','يعرض الموقع تموضع LDU ومنهجيتها وقدراتها وبعض الاعتمادات المختارة لأغراض تجارية ومعلوماتية عامة.'],['أعمال بقيادة المؤسسين','عندما يكون العمل قد نُفذ بواسطة أحد المؤسسين في شركة سابقة، يذكر الموقع ذلك صراحة بصفته عملاً بقيادة المؤسس، ولا يقدمه كعلاقة عميل مباشرة مع LDU.'],['الملكية الفكرية','ما لم يذكر خلاف ذلك، فإن كلمة LDU ورمز الوعل والنظام البصري والنصوص الأصلية والتخطيطات وكود الموقع مواد محمية. لا يمنح الموقع ترخيصاً سوى حق محدود في المشاهدة.'],['وسائط وعلامات الغير','تستخدم أسماء العلامات وعلامات الغير فقط لتحديد الاعتمادات الموثقة، وتبقى حقوق تلك العلامات لأصحابها. لا ينبغي نشر لقطات أو صور فعاليات ما لم تمتلك LDU الحقوق أو الإذن اللازم.'],['لا عرض ملزم أو ضمان','لا يمثل أي محتوى في الموقع عرضاً ملزماً أو وعداً بالتوفر أو ضماناً للأداء أو التزاماً بنتيجة تجارية معينة. يتم الاتفاق على النطاق والرسوم والحقوق والمسؤوليات كتابة بشكل منفصل.'],['الاستخدام المقبول','لا تتدخل في الموقع أو تحاول الوصول غير المصرح به أو ترسل طلبات آلية مسيئة أو تحرف المحتوى أو تزيل النسبة. يتطلب أي اختبار أمني دفاعي موافقة كتابية مسبقة.'],['خدمات خارجية','قد يربط الموقع بخدمات خارجية مثل Instagram أو مزودي التحليلات، وتطبق شروطهم وسياساتهم بشكل مستقل.'],['السياق النظامي','هذه الشروط معدة لموقع نشاط تجاري سعودي وتفسر في سياق الأنظمة السارية في المملكة العربية السعودية، مع مراعاة أي اتفاق ملزم بين الأطراف.'],['التحديثات','يجوز لـLDU تحديث الموقع وهذه الشروط. يوضح التاريخ أعلاه النسخة المنشورة حالياً.'],['التواصل','للاستفسارات التجارية أو الأسئلة المتعلقة بهذه الشروط، استخدم صفحة استقبال المشاريع أو الخط المباشر المنشور في الموقع.']
    ]},
    fr:{eyebrow:'CONDITIONS D’UTILISATION',title:'Utilisez le site. Gardez l’attribution propre.',intro:'Ces conditions régissent l’utilisation du site public LDU. Elles ne remplacent ni proposition, ni SOW, ni contrat, ni accord de droits.',updated:'Dernière mise à jour · 11 septembre 2026',back:'Retour au brief projet ↗',sections:[['Objet du site','Le site présente le positionnement, la méthode, les capacités et certaines références de LDU à des fins générales d’information et de développement commercial.'],['Travaux menés par les fondateurs','Lorsqu’un travail a été livré par un fondateur dans une entreprise précédente, le site le signale comme tel. Ces références ne sont pas présentées comme des missions clients directes de LDU.'],['Propriété intellectuelle','Sauf indication contraire, le nom LDU, l’ibex, le système visuel, les textes originaux, les mises en page et le code sont protégés.'],['Médias et marques tierces','Les noms de marques tierces servent uniquement à identifier des références documentées. Les droits restent à leurs propriétaires. Les images ou vidéos d’événements ne doivent être publiées que si les droits requis sont détenus.'],['Aucune offre ni garantie','Le site ne constitue pas une offre ferme, une garantie de disponibilité, de performance ou de résultat commercial. Le périmètre, les honoraires et les droits sont définis séparément par écrit.'],['Utilisation acceptable','N’interférez pas avec le site, ne tentez pas d’accès non autorisé, n’automatisez pas de requêtes abusives et ne supprimez pas l’attribution.'],['Services externes','Le site peut renvoyer vers Instagram ou des fournisseurs analytics, régis par leurs propres conditions.'],['Cadre juridique','Ces conditions sont conçues pour un site d’entreprise saoudien et doivent être interprétées dans le contexte des lois applicables du Royaume d’Arabie saoudite.'],['Modifications','LDU peut mettre à jour le site et ces conditions. La date ci-dessus indique la version publiée.'],['Contact','Pour toute question commerciale ou relative à ces conditions, utilisez le brief projet ou la ligne directe.']]},
    es:{eyebrow:'TÉRMINOS DE USO DEL SITIO',title:'Usa el sitio. Mantén limpia la atribución.',intro:'Estos términos rigen el uso del sitio público de LDU. No sustituyen una propuesta, SOW, contrato o acuerdo de derechos.',updated:'Última actualización · 11 de septiembre de 2026',back:'Volver al briefing del proyecto ↗',sections:[['Finalidad del sitio','El sitio presenta el posicionamiento, método, capacidades y credenciales seleccionadas de LDU con fines informativos y comerciales generales.'],['Trabajo liderado por fundadores','Cuando un trabajo fue realizado por un fundador en una empresa anterior, el sitio lo etiqueta como tal. No se presenta como una relación directa de cliente con LDU.'],['Propiedad intelectual','Salvo indicación contraria, el nombre LDU, el ibex, el sistema visual, los textos originales, los layouts y el código están protegidos.'],['Medios y marcas de terceros','Los nombres de terceros se usan solo para identificar credenciales documentadas. Sus derechos siguen perteneciendo a sus propietarios. No se debe publicar material de eventos sin los derechos o permisos necesarios.'],['Sin oferta ni garantía','Nada del sitio constituye una oferta vinculante, garantía de disponibilidad, rendimiento o resultado comercial. Alcance, honorarios y derechos se acuerdan por separado y por escrito.'],['Uso aceptable','No interfieras con el sitio, intentes acceso no autorizado, automatices solicitudes abusivas, tergiverses contenido ni elimines atribuciones.'],['Servicios externos','El sitio puede enlazar a Instagram o proveedores de analytics, que aplican sus propios términos y políticas.'],['Contexto legal','Estos términos están diseñados para un sitio empresarial saudí y deben interpretarse en el contexto de las leyes aplicables del Reino de Arabia Saudí.'],['Cambios','LDU puede actualizar el sitio y estos términos. La fecha anterior identifica la versión publicada.'],['Contacto','Para consultas comerciales o sobre estos términos, usa el briefing del proyecto o la línea directa publicada.']]}
  };
  const db={privacy,terms}; const page=document.body.dataset.legal; let lang=localStorage.getItem('ldu-lang'); if(!['en','ar','fr','es'].includes(lang))lang='en';
  function apply(next){if(!['en','ar','fr','es'].includes(next))return;lang=next;localStorage.setItem('ldu-lang',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';const d=db[page][lang]||db[page].en;document.querySelectorAll('[data-k]').forEach(el=>{const k=el.dataset.k;if(d[k])el.textContent=d[k];});const box=document.querySelector('#legalSections');box.innerHTML='';d.sections.forEach((s,i)=>{const sec=document.createElement('section');sec.className='legal-section';const n=document.createElement('span');n.className='n';n.textContent=String(i+1).padStart(2,'0');const wrap=document.createElement('div');const h=document.createElement('h2');h.textContent=s[0];const p=document.createElement('p');p.textContent=s[1];wrap.append(h,p);sec.append(n,wrap);box.append(sec);});document.title=`LDU — ${d.title}`;}
  document.querySelectorAll('[data-legal-lang]').forEach(b=>b.addEventListener('click',()=>apply(b.dataset.legalLang)));apply(lang);
})();
